### ISSUE TITLE
Utf8 keys?

### ISSUE THREAD

**Issue by joagre** [okeuday/trie#8]
I have a need for utf8 keys. How far away is support for these?

**Comment by okeuday** [comment]
@joagre It will work.  It can store any list of integers as a key, so it could be ip addresses and the trie will handle it.  With utf8, if the first letter of the key strings or other later characters in the key strings, have a wide range of integer values (due to many uses of a common prefix), that can cause large tuples to be created, which is slower to modify (still ok read speed), though it will work as expected.

**Comment by joagre** [comment]
Super! Thanks for a great library. Solid work.
